kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-postgres-sc-repl2
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"
   priority_io: "high"
   journal: "false"

---

##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: postgres-data-repl2
   annotations:
     volume.beta.kubernetes.io/storage-class: px-postgres-sc-repl2
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
---


apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  EXAMPLE_DB_HOST: postgres://postgres@postgres/example?sslmode=disable
  EXAMPLE_DB_KIND: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_USER: postgres

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-repl2
spec:
  template:
    metadata:
      labels:
        app: postgres-repl2
    spec:
      schedulerName: stork
      containers:
      - image: "postgres:9.6"
        name: postgres
        envFrom:
        - configMapRef:
            name: example-config
        ports:
        - containerPort: 5432
          name: postgres-repl2
        volumeMounts:
        - name: postgres-data-repl2
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: postgres-data-repl2
        persistentVolumeClaim:
          claimName: postgres-data-repl2
