apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: postgres-3d-snapshot
  annotations:
    stork.rule/pre-snapshot: postgres-3dsnap-prerule
spec:
  persistentVolumeClaimName: postgres-data