# https://docs.portworx.com/scheduler/kubernetes/snaps-3d.html
# https://docs.portworx.com/scheduler/kubernetes/snaps-3d.html#mysql
apiVersion: stork.libopenstorage.org/v1alpha1
kind: Rule
metadata:
  name: px-mysqlwp-presnap-rule
spec:
  - podSelector:
      # Will be replaced by CmdLet Automation
      app: <appName>
    actions:
    - type: command
      # If true, the action will run in background and will be terminated 
      # by Stork after the snapshot has been initiated. 
      # If false, the action will first complete and then the snapshot will get initiated.
      #background: true
      value: <TODO>