---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stresser
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress-container
        image: progrium/stress
        args: ["--cpu", "2", "--io", "2", "--vm", "2", "--vm-bytes", "512M", "--vm-hang", "10"]
