apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: portworx-sc-repl3-2
  namespace: demo
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "medium"
  snap_schedule: "periodic=30,5"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-2
  namespace: demo
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc-repl3-2
  labels:
    app-group: wordpress-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: portworx-sc-repl3-shared-2
  namespace: demo
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "medium"
  shared: "true"
  io_profile: "cms"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim-2
  namespace: demo
  labels:
    app: wordpress-2
    app-group: wordpress-2
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc-repl3-shared-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

