apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-2
  namespace: demo
  labels:
    app: wordpress-2
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-2
    tier: mysql-2
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-mysql-2
  namespace: demo
  labels:
    app: wordpress-2
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-2
        tier: mysql-2
    spec:
      # Use the stork scheduler to enable more efficient placement of the pods
      schedulerName: stork
      containers:
      - image: mysql:5.6
        imagePullPolicy: 
        name: mysql-2
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-2
              key: mysqlpasswd.txt
        ports:
        - containerPort: 3306
          name: mysql-2
        volumeMounts:
        - name: mysql-persistent-storage-2
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-2
        persistentVolumeClaim:
          claimName: mysql-pvc-2
